#!/bin/bash
# Combines the png images with the AGs from two different directories (presumably, generated by original and modified SAGE algorithm respectively).
# The png images are put horizontally side-by-side. The resulting images will be in the directory `combined-ExpName1-ExpName2AGs/`,
#   assuming that the input directories are ExpName1AGs/ and ExpName2AGs/ respectively.
# Only the AGs present in both directories are combined. The ones that are present only in one of the directories are ignored.
#
# NB! This script assumes that the directory with the AGs has the name ExpNameAGs/ and that the AG files also have ExpName in their name (i.e. the name has not been changed).
#     To avoid potential errors, please only use alphanumeric characters in the name of the experiments (i.e. no whitespaces, enters etc.).

set -euo pipefail
IFS=$'\n\t'

umask 077

function usage(){
    echo "Usage: $0 path/to/AGs path/to/AGs"
}

# Check if exactly two arguments are provided
[[ $# -ne 2 ]] && { usage >&2 ; exit 1; }

# Check if all input directories exist
dir_original=$(echo "$1/" | tr -s '/')
dir_modified=$(echo "$2/" | tr -s '/')
! [[ -d "$dir_original" ]] && { echo "$0: directory $dir_original does not exist" >&2 ; exit 1 ; }
! [[ -d "$dir_modified" ]] && { echo "$0: directory $dir_modified does not exist" >&2 ; exit 1 ; }

# Check the dependency
convert --help > /dev/null

# Resolve experiment names (i.e. remove the `AGs` part from the names of the directories)
exp_original=$(echo "$dir_original" | sed 's@AGs/@@')
exp_modified=$(echo "$dir_modified" | sed 's@AGs/@@')

# Create the output directory if it does not already exist
dir_output="combined-${exp_original}-${exp_modified}AGs/"
[[ -d "$dir_output" ]] && { echo "$0: output directory $dir_output already exists" >&2 ; exit 1; }
mkdir "$dir_output" || { echo "$0: failed creating output directory $dir_output" >&2 ; exit 1; }

# This is the prefix used in every AG file name (ExpName-prefix-victim-mcatmserv)
prefix="-attack-graph-for-victim-"

# Actually combine the png images with the corresponding AGs
# First, find the AGs that are present in both directories (compare the file names without the experiment name and the prefix)
comm -12 <(find "$dir_original" -type f -name '*.png' -printf '%f\n' | sed 's@'"${exp_original}\.txt${prefix}"'@@' | sort)\
         <(find "$dir_modified" -type f -name '*.png' -printf '%f\n' | sed 's@'"${exp_modified}\.txt${prefix}"'@@' | sort) |
         sed 's@^\(.*\)$@convert +append '"${dir_original}${exp_original}\.txt${prefix}"'\1 '"${dir_modified}${exp_modified}\.txt${prefix}"'\1 '"$dir_output"'\1@' |    # Create the commands for the shell
         sh                                                                                                                                                             # Execute these commands 

