#!/bin/bash
# Compares two directories with AGs (presumably, generated by original and modified SAGE algorithm respectively).
# Prints how many AGs are present in each directory, how many AGs are present in both directories,
#   and how many AGs are present only in the first and only in the second directories.
# If at least one AG is present in only in one of the directories, it is also printed.
#
# NB! The comparison is based on .dot files, which are by default deleted during the execution of SAGE.
#      To prevent the deletion, set DOCKER to False.

set -euo pipefail
IFS=$'\n\t'

umask 077

usage="usage: $0 directory1/ directory2/"

[[ $# -ne 2 ]] && { echo $usage >&2 ; exit 1; }

original=$(echo $1/ | tr -s '/')
modified=$(echo $2/ | tr -s '/')

! [[ -d "$original" ]] && { echo "$0: directory $original does not exist" >&2 ; exit 1 ; }
! [[ -d "$modified" ]] && { echo "$0: directory $modified does not exist" >&2 ; exit 1 ; }

original_ags=$(find "$original" -type f -name '*.dot' -printf '%f\n' | sed 's/^.*attack-graph-for-victim-\(.*\)$/\1/' | sort)
modified_ags=$(find "$modified" -type f -name '*.dot' -printf '%f\n' | sed 's/^.*attack-graph-for-victim-\(.*\)$/\1/' | sort)

echo -n "Total number of AGs generated the original algorithm: "
echo -e "$original_ags" | wc -l

echo -n "Total number of AGs generated the modified algorithm: "
echo -e "$modified_ags" | wc -l

echo -n "Number of AGs generated both by the original and the modified algorithms: "
comm -12 <(echo -e "$original_ags") <(echo -e "$modified_ags") | wc -l

echo -n "Number of AGs generated only by the original algorithm: "
only_original=$(comm -23 <(echo -e "$original_ags") <(echo -e "$modified_ags") | wc -l)
echo "$only_original"
if [[ $only_original -ne 0 ]]; then
    echo "AGs generated only by the original algorithm: "
    comm -23 <(echo -e "$original_ags") <(echo -e "$modified_ags")
fi

echo -n "Number of AGs generated only by the modified algorithm: "
only_modified=$(comm -13 <(echo -e "$original_ags") <(echo -e "$modified_ags") | wc -l)
echo "$only_modified"
if [[ $only_modified -ne 0 ]]; then
    echo "AGs generated only by the modified algorithm: "
    comm -13 <(echo -e "$original_ags") <(echo -e "$modified_ags")
fi

