#!/bin/bash
# Compares two AGs based on the nodes they have (presumably, AGs generated by the original and modified algorithms respectively).
# The computed statistics are (when running in normal mode, i.e. with no options):
#   - Nodes found by both algorithms
#   - Nodes found only by the original algorithm
#   - Nodes found only by the modified algorithm
# If running in quiet mode (i.e. option -q , inspired by the "quick diff"), the script:
#   - Prints that the graphs are different if at least one node has been found by only one of the algorithms (exit code 1)
#   - Prints nothing if there are no nodes found by only one of the algorithms (exit code 0)
#
# Note: The comparison is purely based on the nodes of the graphs (their names, to be precise).
#       If two nodes with the same name are present in different places in the AGs (e.g at the beginning and end of a path),
#         they are still considered the same.
#       The 'ID' is removed from the node name, since it is likely to be different for original and modified graphs
#         even if the states are the same.
#
# NB! This script is based on .dot files, which are by default deleted during the execution of SAGE.
#      To prevent the deletion, set the DOCKER variable to False (in SAGE).

set -euo pipefail
IFS=$'\n\t'

umask 077

usage() {
    echo -e "Usage: $0 [-q] originalAG.dot modifiedAG.dot\n\n\t-q\treport only when attack graphs differ (do not print differences)"
}

# If two arguments are provided, assume "normal" mode
if [[ $# -eq 2 ]]; then 
    original="$1"
    modified="$2"
    mode="normal"
# If three arguments are provided, assume "quiet" mode (the first argument has to be the option -q)
elif [[ $# -eq 3 ]]; then
    while getopts "q" option; do
        case ${option} in
            q ) mode="quiet" ;;
            \? ) { usage >&2; exit 1; } ;;
        esac
    done

    original="$2"
    modified="$3"
# The number of arguments can only be two or three
else
    usage >&2
    exit 1
fi

# Check if all input directories exist and that both files have .dot extension
! [[ -f "$original" ]] && { echo "$0: file $original does not exist" >&2 ; exit 1 ; }
! [[ -f "$modified" ]] && { echo "$0: file $modified does not exist" >&2 ; exit 1 ; }
! [[ "${original##*.}" == "dot" ]] && { echo "$0: file $original is not a .dot file" >&2 ; exit 1 ; }
! [[ "${modified##*.}" == "dot" ]] && { echo "$0: file $modified is not a .dot file" >&2 ; exit 1 ; }

# Get the nodes generated by the original and modified algorithms (format: mcat|mserv ; for root node, victim IP is prepended to the name)
nodes_original=$(gvpr 'N { print(gsub(gsub($.name, "\r"), "\n", "|")) }' "$original" | sed 's/ | ID: .*//g' | sed 's/^Victim: //' | tr ' ' '_' | sort)
nodes_modified=$(gvpr 'N { print(gsub(gsub($.name, "\r"), "\n", "|")) }' "$modified" | sed 's/ | ID: .*//g' | sed 's/^Victim: //' | tr ' ' '_' | sort)

# Find the nodes that are common and nodes that are present in only one of the graphs
only_original=$(comm -23 <(echo -e "$nodes_original") <(echo -e "$nodes_modified"))
only_modified=$(comm -13 <(echo -e "$nodes_original") <(echo -e "$nodes_modified"))
common=$(comm -12 <(echo -e "$nodes_original") <(echo -e "$nodes_modified"))

# When running in quiet mode, report if the graphs are different or exit quietly if they are the same
if [[ "$mode" == "quiet" ]]; then
    if [[ -z "$only_original" ]] && [[ -z $only_modified ]]; then
        exit 0;
    else
        echo "Attack graphs $original and $modified are different"
        exit 1
    fi
fi

# When running in normal mode, show the common nodes and nodes that are present in only one of the graphs (and their counts)
# Common nodes (i.e. present in both graphs)
echo "Nodes found by both algorithms: $(echo -e "$common" | wc -l)"
echo -e "$common"
echo -ne "\n"

# Nodes only present in the original graph
if ! [[ -z "$only_original" ]]; then
    echo "Nodes found only by original algorithm: $(echo -e "$only_original" | wc -l)"
    echo -e "$only_original"
else
    echo "Nodes found only by original algorithm: 0"
fi

# Nodes only present in the modified graph
if ! [[ -z "$only_modified" ]]; then
    echo -ne "\n"
    echo "Nodes found only by modified algorithm: $(echo -e "$only_modified" | wc -l)"
    echo -e "$only_modified"
else
    echo "Nodes found only by modified algorithm: 0"
fi

