#!/bin/bash
# Computes the number of red, blue and white nodes generated by the FlexFringe algorithm.
# First it resolves the experiment name to the corresponding FlexFringe .dot files and then computes the statistics.
#
# NB! The statistics are computed on .dot files, which are by default deleted during the execution of SAGE
#      To prevent the deletion, set the variable DOCKER to False

set -euo pipefail
IFS=$'\n\t'

umask 077

usage="usage: $0 ExpName"

[[ $# -ne 1 ]] && { echo $usage >&2 ; exit 1; }

core="${1}.txt.ff.final.dot"
sinks="${1}.txt.ff.finalsinks.dot"

! [[ -f "$core" ]] && { echo "$0: file $core does not exits" >&2 ; exit 1 ; }
! [[ -f "$sinks" ]] && { echo "$0: file $sinks does not exits" >&2 ; exit 1 ; }

red=$(gvpr -q 'N [ $.fillcolor == "firebrick1" ] { print($.name) }' $core | wc -l)
blue=$(gvpr -q 'N [ $.fillcolor == "dodgerblue1" ] { print($.name) }' $sinks | wc -l)
white=$(gvpr -q 'N [ $.fillcolor == "ghostwhite" ] { print($.name) }' $sinks | wc -l)
total=$((red + blue + white))

echo "Total red states (core): $red ($(echo "scale=3; 100 * $red / $total" | bc)%)"
echo "Total blue states: $blue ($(echo "scale=3; 100 * $blue / $total" | bc)%)"
echo "Total white states (sinks): $white ($(echo "scale=3; 100 * $white / $total" | bc)%)"
echo "Total states (red + blue + white): $total"

