#!/bin/bash
# Combines the png images with the AGs from two different directories (presumably, generated by original and modified SAGE algorithm respectively)
# The png images are put horizontally side-by-side. The resulting images will be in the directory `combined-ExpName1-ExpName2AGs/`
# Only the AGs present in both directories are combined. The ones that are present only in one of the directories are ignored
#
# NB! DO NOT DELETE ExpName.txt FILE GENERATED BY SAGE
#     In addition, this scripts assumes that the directory with the AGs has the name ExpNameAGs/
#     To avoid errors, please only use alphanumeric characters in the name of the experiments (i.e. no whitespaces, enters etc.)

set -euo pipefail
IFS=$'\n\t'

umask 077

usage="usage: $0 path/to/AGs path/to/AGs"

[[ $# -ne 2 ]] && { echo $usage >&2 ; exit 1; }

dir_original=$(echo "$1/" | tr -s '/')
dir_modified=$(echo "$2/" | tr -s '/')

! [[ -d "$dir_original" ]] && { echo "$0: directory $dir_original does not exist" >&2 ; exit 1 ; }
! [[ -d "$dir_modified" ]] && { echo "$0: directory $dir_modified does not exist" >&2 ; exit 1 ; }

exp_original=$(echo "$dir_original" | sed 's@AGs/@@')
exp_file_original="${exp_original}.txt"
! [[ -f "$exp_file_original" ]] && { echo "$0: file $exp_file_original does not exist" >&2 ; exit 1 ; }

exp_modified=$(echo "$dir_modified" | sed 's@AGs/@@')
exp_file_modified="${exp_modified}.txt"
! [[ -f "$exp_file_modified" ]] && { echo "$0: file $exp_file_modified does not exist" >&2 ; exit 1 ; }

dir_output="combined-${exp_original}-${exp_modified}AGs/"
[[ -d "$dir_output" ]] && { echo "$0: output directory $dir_output already exists" >&2 ; exit 1; }
mkdir "$dir_output" || { echo "$0: failed creating output directory $dir_output" >&2 ; exit 1; }

prefix="-attack-graph-for-victim-"

comm -12 <(find "$dir_original" -type f -name '*.png' -printf '%f\n' | sed 's@'"${exp_file_original}${prefix}"'@@' | sort)\
         <(find "$dir_modified" -type f -name '*.png' -printf '%f\n' | sed 's@'"${exp_file_modified}${prefix}"'@@' | sort) |
         sed 's@^\(.*\)$@convert +append '"${dir_original}${exp_file_original}${prefix}"'\1 '"${dir_modified}${exp_file_modified}${prefix}"'\1 '"$dir_output"'\1@' |
         sh

