#!/bin/bash
# Combines the png images with the AGs from two different directories (presumably, generated by original and modified SAGE algorithm respectively)
# The png images are put horizontally side-by-side. The resulting images will be in the directory `combined-ExpName1-ExpName2AGs/`
# Only the AGs present in both directories are combined. The ones that are present only in one of the directories are ignored
#
# NB! DO NOT DELETE ExpName.txt FILE GENERATED BY SAGE
#     In addition, this scripts assumes that the directory with the AGs has the name ExpNameAGs/
#     To avoid errors, please only use alphanumeric characters in the name of the experiments (i.e. no whitespaces, enters etc.)

set -euo pipefail
IFS=$'\n\t'

umask 077

usage="usage: $0 path/to/AGs path/to/AGs"

[[ $# -ne 2 ]] && { echo $usage >&2 ; exit 1; }

DIR_ORIGINAL=$(echo "$1/" | tr -s '/')
DIR_MODIFIED=$(echo "$2/" | tr -s '/')

! [[ -d "$DIR_ORIGINAL" ]] && { echo "$0: directory $DIR_ORIGINAL does not exits" >&2 ; exit 1 ; }
! [[ -d "$DIR_MODIFIED" ]] && { echo "$0: directory $DIR_MODIFIED does not exits" >&2 ; exit 1 ; }

EXP_ORIGINAL=$(echo "$DIR_ORIGINAL" | sed 's@AGs/@@')
EXP_FILE_ORIGINAL="${EXP_ORIGINAL}.txt"
! [[ -f "$EXP_FILE_ORIGINAL" ]] && { echo "$0: file $EXP_FILE_ORIGINAL does not exits" >&2 ; exit 1 ; }

EXP_MODIFIED=$(echo "$DIR_MODIFIED" | sed 's@AGs/@@')
EXP_FILE_MODIFIED="${EXP_MODIFIED}.txt"
! [[ -f "$EXP_FILE_MODIFIED" ]] && { echo "$0: file $EXP_FILE_MODIFIED does not exits" >&2 ; exit 1 ; }

DIR_OUTPUT="combined-${EXP_ORIGINAL}-${EXP_MODIFIED}AGs/"
[[ -d "$DIR_OUTPUT" ]] && { echo "$0: output directory $DIR_OUTPUT already exists" >&2 ; exit 1; }
mkdir "$DIR_OUTPUT" || { echo "$0: failed creating output directory $DIR_OUTPUT" >&2 ; exit 1; }

PREFIX="-attack-graph-for-victim-"

comm -12 <(find "$DIR_ORIGINAL" -type f -name '*.png' -printf '%f\n' | sed 's@'"${EXP_FILE_ORIGINAL}${PREFIX}"'@@' | sort)\
         <(find "$DIR_MODIFIED" -type f -name '*.png' -printf '%f\n' | sed 's@'"${EXP_FILE_MODIFIED}${PREFIX}"'@@' | sort) |
         sed 's@^\(.*\)$@convert +append '"${DIR_ORIGINAL}${EXP_FILE_ORIGINAL}${PREFIX}"'\1 '"${DIR_MODIFIED}${EXP_FILE_MODIFIED}${PREFIX}"'\1 '"$DIR_OUTPUT"'\1@' |
         sh

