#!/bin/bash
# Compares two AGs based on the edges they have (presumably, AGs generated by the original and modified algorithms respectively)
# The computed statistics are (when running in normal mode, i.e. with no options):
#   - Edges found by both algorithms
#   - Edges found only by the original algorithm
#   - Edges found only by the modified algorithm
# If running in quiet mode (i.e. option -q , inspired by quick diff), the script:
#   - Prints that the graphs are different if at least one edge has been found by only one of the algorithms (exit code 1)
#   - Prints nothing if there are no edges found by only one of the algorithms (exit code 0)
#
# Note: The comparison is purely based on the edges of the graphs (their names and labels, to be precise).
#       If two edges are the same but are present in different places in the AGs (e.g at the beginning and end of a path), they are considered the same.
#
# NB! The comparison is based on .dot files, which are by default deleted during the execution of SAGE.
#      To prevent this deletion, set DOCKER to False.

set -euo pipefail
IFS=$'\n\t'

umask 077

usage="usage: $0 [-q] originalAG.dot modifiedAG.dot"

if [[ $# -eq 2 ]]; then 
    original="$1"
    modified="$2"
    mode="normal"
elif [[ $# -eq 3 ]]; then
    while getopts "q" option; do
        case ${option} in
            q ) mode="quiet" ;;
            \? ) { echo $usage >&2; exit 1; } ;;
        esac
    done

    original="$2"
    modified="$3"
else
    echo $usage >&2
    exit 1
fi

! [[ -f "$original" ]] && { echo "$0: file $original does not exist" >&2 ; exit 1 ; }
! [[ -f "$modified" ]] && { echo "$0: file $modified does not exist" >&2 ; exit 1 ; }
! [[ "${original##*.}" == "dot" ]] && { echo "$0: file $original is not a .dot file" >&2 ; exit 1 ; }
! [[ "${modified##*.}" == "dot" ]] && { echo "$0: file $modified is not a .dot file" >&2 ; exit 1 ; }

# Put the name of the edge (i.e. "src->dst") next to the label of the edge (time metadata), separated by a "#"
parse_edges(){
    paste -d '#' <(gvpr 'E { print(gsub(gsub($.name, "\r"), "\n", "|")); }' "$1" | sed 's/ | ID: -\?[0-9]\+//g' | sed 's/Victim: //' | tr ' ' '_')\
                 <(gvpr 'E { print(gsub(gsub($.label, "\r"), "\n", ", ")) }' "$1" | sed '/^$/d' | sed 's@<br/>@, @g' | sed 's/<[^>]*>//g' | sed 's/^ \+//') |
            sed 's/->/ -> /g' | sed 's/#/ \# /g' | sort
}

edges_original=$(parse_edges $original)
edges_modified=$(parse_edges $modified)

only_original=$(comm -23 <(echo -e "$edges_original") <(echo -e "$edges_modified"))
only_modified=$(comm -13 <(echo -e "$edges_original") <(echo -e "$edges_modified"))
common=$(comm -12 <(echo -e "$edges_original") <(echo -e "$edges_modified"))

# Running in quiet mode
if [[ "$mode" == "quiet" ]]; then
    if [[ -z "$only_original" ]] && [[ -z $only_modified ]]; then
        exit 0;
    else
        echo "Attack graphs $original and $modified are different" >&2 
        exit 1
    fi
fi

# Running in normal mode
echo "Edges found by both algorithm: $(echo -e "$common" | wc -l)"
echo -e "$common"
echo -ne "\n"

if ! [[ -z "$only_original" ]]; then
    echo "Edges found only by original algorithm: $(echo -e "$only_original" | wc -l)"
    echo -e "$only_original"
else
    echo "Edges found only by original algorithm: 0"
fi

if ! [[ -z "$only_modified" ]]; then
    echo -ne "\n"
    echo "Edges found only by modified algorithm: $(echo -e "$only_modified" | wc -l)"
    echo -e "$only_modified"
else
    echo "Edges found only by modified algorithm: 0"
fi
