#!/bin/bash
# Computes the number of red, blue and white nodes generated by the FlexFringe algorithm
#
# NB! The comparison is based on .dot files, which are by default deleted during the execution of SAGE
#      To prevent deletion, set the variable DOCKER to False

set -euo pipefail
IFS=$'\n\t'

umask 077

usage="usage: $0 ExpName"

[[ $# -ne 1 ]] && { echo $usage >&2 ; exit 1; }

CORE="${1}.txt.ff.final.dot"
SINKS="${1}.txt.ff.finalsinks.dot"

! [[ -f "$CORE" ]] && { echo "$0: file $CORE does not exits" >&2 ; exit 1 ; }
! [[ -f "$SINKS" ]] && { echo "$0: file $SINKS does not exits" >&2 ; exit 1 ; }

red=$(gvpr 'N [ fillcolor == "firebrick1" ] { print($.name) }' $CORE | wc -l)
blue=$(gvpr 'N [ fillcolor == "dodgerblue1" ] { print($.name) }' $SINKS | wc -l)
white=$(gvpr 'N [ fillcolor == "ghostwhite" ] { print($.name) }' $SINKS | wc -l)
total=$((red + blue + white))

echo "Total red states (core): $red ($(echo "scale=3; 100 * $red / $total" | bc)%)"
echo "Total blue states: $blue ($(echo "scale=3; 100 * $blue / $total" | bc)%)"
echo "Total white states (sinks): $white ($(echo "scale=3; 100 * $white / $total" | bc)%)"
echo "Total states (red + blue + white): $total"

